### ISSUE TITLE
Spamfilter blockiert update

### ISSUE THREAD

**Issue by DrCarsonBeckett** [derUli/oneclick_upgrade#16]
Moin,

der Spamfilter blockiert das One Click Upgrade, sobald eine minimale Bearbeitungsdauer aktiviert wird.
Wird diese entfernt, funktioniert es sofort.

Viele Grüße

**Comment by derUli** [comment]
Unter folgendem Link findest du eine korrigierte Version von oneclick_upgrade
http://extend.ulicms.de/content/files/packages/oneclick_upgrade/oneclick_upgrade-1.7.sin
Bitte installiere dieses Paket und bestätige mir, ob das das Problem für dich löst.
Wenn du bereits die neueste UliCMS Version hast, kannst du die Datei UliCMSVersion.php durch die aus der vorherigen Version ersetzen, um eine erneute Durchführung des Upgrades zu erzwingen.

**Comment by DrCarsonBeckett** [comment]
Hat damit geklappt.

**Comment by derUli** [comment]
Dann werde ich das Update für das Modul demnächst im eXtend Downloadportal veröffentlichen

**Comment by derUli** [comment]
Neue Version 1.7
https://extend.ulicms.de/oneclick_upgrade.html
